import { useState, useCallback, useRef } from 'react';

function fmtD(n) {
  if (n == null) return '--';
  if (Math.abs(n) >= 1e6) return `$${(n / 1e6).toFixed(2)}M`;
  if (Math.abs(n) >= 1e3) return `$${Math.round(n / 1e3).toLocaleString()}K`;
  return `$${Math.round(n).toLocaleString()}`;
}

export default function ShareButton({ projections, totals, otmPercent, expirationDate, coverage }) {
  const [open, setOpen] = useState(false);
  const [generating, setGenerating] = useState(false);
  const sheetRef = useRef(null);

  const getDateStr = () => new Date().toISOString().slice(0, 10);
  const otmLabel = otmPercent === 0 ? 'ATM' : `${Math.round(otmPercent * 100)}% OTM`;
  const coverageLabel = `${Math.round(coverage * 100)}%`;
  const expiryLabel = expirationDate.slice(0, 7);

  // Build text summary
  const buildSummary = useCallback(() => {
    const lines = [
      'Covered Jim — Premium Projection',
      `As of: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
      '',
      `Strategy: ${otmLabel}, ${expiryLabel} LEAPS, ${coverageLabel} coverage`,
      `Total upfront premium: ${fmtD(totals.totalUpfront)}`,
      `Annualized premium: ${fmtD(totals.totalAnnualized)}`,
      `Annualized yield: ${totals.annualizedYieldOnMV.toFixed(1)}% on market value`,
      '',
      'Per-ticker breakdown:',
    ];
    for (const p of projections.filter(p => p.optionable && p.status === 'ok')) {
      lines.push(`  ${p.ticker}: ${fmtD(p.totalPremium)} upfront / ${fmtD(p.annualizedPremium)} annualized (${p.contracts}c @ $${p.actualStrike})`);
    }
    lines.push('', 'Generated by Covered Jim. Projections based on live market data, not guaranteed.');
    return lines.join('\n');
  }, [projections, totals, otmLabel, expiryLabel, coverageLabel]);

  const handleCopy = useCallback(async () => {
    const text = buildSummary();
    try {
      await navigator.clipboard.writeText(text);
      setOpen(false);
    } catch {
      // Fallback
      const ta = document.createElement('textarea');
      ta.value = text;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
      setOpen(false);
    }
  }, [buildSummary]);

  const handleShareText = useCallback(async () => {
    const text = buildSummary();
    if (navigator.share) {
      try {
        await navigator.share({ title: 'Covered Jim — Premium Projection', text });
      } catch {}
    } else {
      await handleCopy();
    }
    setOpen(false);
  }, [buildSummary, handleCopy]);

  const handlePDF = useCallback(async () => {
    setGenerating(true);
    try {
      const [{ default: html2canvas }, { jsPDF }] = await Promise.all([
        import('html2canvas'),
        import('jspdf'),
      ]);

      // Capture the main content area
      const el = document.getElementById('export-region');
      if (!el) { setGenerating(false); return; }
      const canvas = await html2canvas(el, { scale: 2, useCORS: true, backgroundColor: '#ffffff' });
      const imgData = canvas.toDataURL('image/png');

      const pdf = new jsPDF('p', 'mm', 'letter');
      const pageW = pdf.internal.pageSize.getWidth();
      const pageH = pdf.internal.pageSize.getHeight();
      const imgW = pageW - 20;
      const imgH = (canvas.height / canvas.width) * imgW;

      pdf.setFontSize(16);
      pdf.text('Covered Jim — Premium Projection', 10, 12);
      pdf.setFontSize(9);
      pdf.text(`${otmLabel} | ${expiryLabel} LEAPS | ${coverageLabel} coverage | ${new Date().toLocaleDateString()}`, 10, 18);

      if (imgH < pageH - 30) {
        pdf.addImage(imgData, 'PNG', 10, 22, imgW, imgH);
      } else {
        pdf.addImage(imgData, 'PNG', 10, 22, imgW, pageH - 32);
      }

      pdf.setFontSize(7);
      pdf.text('Generated by Covered Jim. Projections based on live market data, not guaranteed.', 10, pageH - 5);

      const blob = pdf.output('blob');
      const file = new File([blob], `Covered-Jim-${getDateStr()}.pdf`, { type: 'application/pdf' });

      if (navigator.share && navigator.canShare?.({ files: [file] })) {
        await navigator.share({ files: [file], title: 'Covered Jim Projection' });
      } else {
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = file.name;
        a.click();
        URL.revokeObjectURL(url);
      }
    } catch (err) {
      console.error('PDF generation failed:', err);
    }
    setGenerating(false);
    setOpen(false);
  }, [otmLabel, expiryLabel, coverageLabel]);

  return (
    <>
      <button onClick={() => setOpen(true)} disabled={generating}
        className="min-h-[44px] min-w-[44px] flex items-center justify-center rounded-lg border border-gray-200 text-gray-500 active:bg-gray-100">
        {generating ? (
          <span className="text-xs">...</span>
        ) : (
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8" />
            <polyline points="16 6 12 2 8 6" />
            <line x1="12" y1="2" x2="12" y2="15" />
          </svg>
        )}
      </button>

      {/* Bottom sheet */}
      {open && (
        <div className="fixed inset-0 z-50" onClick={() => setOpen(false)}>
          <div className="absolute inset-0 bg-black/30" />
          <div className="absolute bottom-0 left-0 right-0 bg-white rounded-t-2xl shadow-xl p-4 pb-8 space-y-2"
            style={{ paddingBottom: `max(2rem, env(safe-area-inset-bottom))` }}
            onClick={e => e.stopPropagation()}>
            <div className="w-10 h-1 bg-gray-300 rounded-full mx-auto mb-3" />
            <div className="text-sm font-semibold text-gray-900 mb-2">Share Projection</div>

            <button onClick={handlePDF} disabled={generating}
              className="w-full flex items-center gap-3 px-4 py-3 rounded-lg text-left active:bg-gray-100 min-h-[48px]">
              <span className="text-lg">📄</span>
              <div>
                <div className="text-sm font-medium text-gray-900">Share as PDF</div>
                <div className="text-xs text-gray-500">Professional format for email or print</div>
              </div>
            </button>

            <button onClick={handleShareText}
              className="w-full flex items-center gap-3 px-4 py-3 rounded-lg text-left active:bg-gray-100 min-h-[48px]">
              <span className="text-lg">💬</span>
              <div>
                <div className="text-sm font-medium text-gray-900">Share as Text</div>
                <div className="text-xs text-gray-500">Quick share via Messages, Slack, email</div>
              </div>
            </button>

            <button onClick={handleCopy}
              className="w-full flex items-center gap-3 px-4 py-3 rounded-lg text-left active:bg-gray-100 min-h-[48px]">
              <span className="text-lg">📋</span>
              <div>
                <div className="text-sm font-medium text-gray-900">Copy Summary</div>
                <div className="text-xs text-gray-500">Copy text to clipboard for pasting</div>
              </div>
            </button>

            <button onClick={() => setOpen(false)}
              className="w-full text-center text-sm text-gray-500 py-3 mt-2 active:bg-gray-100 rounded-lg min-h-[44px]">
              Cancel
            </button>
          </div>
        </div>
      )}
    </>
  );
}
